### ISSUE TITLE
Creation hangs if Github default branch is not `master`

### ISSUE THREAD

**Issue by pchinjr** [smallwins/begin-community#16]
**Expected behavior**
Begin apps would deploy from master

**Description of bug**
When the default branch is not set to master, then the deploy process will hang indefinitely. 

**Steps to reproduce**
- create a repo on Github
- create a `develop` branch
- use repo settings to set default branch to develop
![image](https://user-images.githubusercontent.com/10526646/76364265-1e20c980-62fb-11ea-9baf-72e441c9d6b3.png)
- create new Begin app from existing repo

**Screenshots**
App will remain on fetching git repo step
![image](https://user-images.githubusercontent.com/10526646/76364312-37c21100-62fb-11ea-9733-d7e4e5ddb6a3.png)

**Additional context or notes**
If a default branch is changed after a successful deploy, begin will not deploy future pushes to master. 
This is my test app https://github.com/pchinjr/begin-different-default-branch

**Comment by ryanblock** [comment]
We're overdue to fix this feature, especially since we're all going to be moving on from `master` soon enough (and rightfully so).

**Comment by ryanblock** [comment]
Good news! The first version of this shipped last week. Anyone can now change their default branch to any name (and even associate new apps with existing repos that use a default branch of any name) and it will be automatically picked up and used by Begin.

This is a nice improvement for customization, and a small step forward in promoting the use of inclusive language and terminology within our industry.
