### ISSUE TITLE
Add scheduled functions (aka @scheduled, cron)

### ISSUE THREAD

**Issue by ryanblock** [smallwins/begin-community#27]
We recently added [event functions](https://blog.begin.com/a-brand-new-primitive-for-your-begin-apps-event-functions-9cdfd2bb3dcb) – next up, by popular demand: scheduled!

You should be able to run scheduled functions at any cadence (paid-tier), or up to some limited number of times per day (free-tier).

**Comment by searchy2** [comment]
Wow, this would be game changing. Looking forward to it!

**Comment by ryanblock** [comment]
@searchy2 would you like to trial it as well?

**Comment by searchy2** [comment]
Thanks for the offer! Unfortunately, I don't have the bandwidth at the moment but the feature would enable a bunch of use cases I have in mind.

- Routinely validate the response from an endpoint.
- Run cron jobs.
- Aggregate data periodically.
- Process queues.

**Comment by ryanblock** [comment]
Good news y'all, `@scheduled` shipped this week!

- Reference: https://docs.begin.com/en/scheduled-functions/provisioning
- How-to guide: https://docs.begin.com/en/guides/scheduled

Can't wait to hear what you think!
