### ISSUE TITLE
@static folder specified with a subdirectory may not deploy assets

### ISSUE THREAD

**Issue by ryanblock** [smallwins/begin-community#43]
**Expected behavior**
```
@static
folder foo/bar
```
Should deploy the static assets found in `foo/bar/*`

**Description of bug**
In the above scenario, not everything (or even nothing) may be deployed.

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Create a project with no `get /` and:
```
@static
folder foo/bar
```
2. Put files in `foo/bar/`
3. Deploy it
4. Those files should fail to load

**Comment by brianleroux** [comment]
Ooof. I am so embarrassed this use case never occurred 😬 … on it! (Thx for being our canary @sw-yx will get this resolved ASAP.)

**Comment by sw-yx** [comment]
np np. got to hammer on it from a variety of ways to smooth out edges.

what i recommended to the render.com folks was that they should set up nightly acceptance tests for the basic hello world projects in every community they cater to. Svelte is small but given your alignment with the new-n-fancy it will probably be overrepresented.

**Comment by brianleroux** [comment]
Fixes on prod /lmk if anything like this pops up. Static asset flows definitely not a primary use case we designed for and sometimes it embarrassingly shows up like this. As folks cross the chasm to cloud functions hopefully won't matter but in the meantime we really want to be excellent at this so again really appreciate the help. Cheers!
