### ISSUE TITLE
Event functions log view/ui not collecting event logs for staging or production.

### ISSUE THREAD

**Issue by ShawnHosea** [smallwins/begin-community#44]
**Expected behavior**
After spinning up the begin node-events example and deploying to staging and production, I should be able to see event logs in my Begin backend after interacting with my app in either staging or production.

**Description of bug**
Event logs not logging any events from apps in staging or production

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Git clone this repo: https://github.com/begin-examples/node-events
2. Clone it with Begin
3. Git commit and push to staging and production.
4. Interact with app in either staging or production.
4. Click events tab In Begin backend and check for logs after interacting with app. 

**Screenshots**
<img width="1386" alt="Screen Shot 2020-05-21 at 7 48 46 AM" src="https://user-images.githubusercontent.com/36789673/82556346-8c71db80-9b37-11ea-88d6-1df3a19cdbb2.png">

**Additional context or notes**
Add any other context or notes about the problem here.

**Comment by ryanblock** [comment]
I think this was a false alarm, with a behavioral disparity between the log output of Sandbox and the actual AWS logs. Everything here should be functioning normally.
