### ISSUE TITLE
Scheduled functions guide appears to be broken

### ISSUE THREAD

**Issue by fillipvt** [smallwins/begin-community#57]
**Expected behavior**
After following the guide for scheduled functions, the number of views in the deployed website should be shown.

**Description of bug**
The guide mentions in the section "Your first deploy" that:
"Go ahead and click the Staging link in the upper left corner of your left nav to open your new app's staging URL. You should now see your new app:"

But what's actually seen in the staging URL [is this](https://forest-cou-staging.begin.app/):
<img width="1268" alt="Screen Shot 2020-10-27 at 5 53 21 PM" src="https://user-images.githubusercontent.com/16828078/97370583-50c50580-187d-11eb-88f5-505df229fda3.png">

There's no view count and the scheduled functions section in the app only shows `Count: 1` no matter how many times I reload the front end page.
<img width="1268" alt="Screen Shot 2020-10-27 at 5 54 28 PM" src="https://user-images.githubusercontent.com/16828078/97370644-78b46900-187d-11eb-9a80-2b61dac360fe.png">

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Connect with GitHub
2. Follow the [guide](https://docs.begin.com/en/guides/scheduled)

**Device**
- Device: MacBook Pro (15-inch, 2018)
- OS: macOS
- Browser: Firefox 82.0

**Additional context or notes**
First time doing anything with Begin

**Comment by brianleroux** [comment]
Hey @fillipvt … can you share the `.arc` or `app.arc` file you have ? We limit free tier to `rate(6 hours)` currently but are open to changing that.

**Comment by fillipvt** [comment]
[This](https://github.com/fillipvt/begin-scheduled-functions-app/blob/main/app.arc) should be it. I'm only using the default values, haven't changed anything yet

**Comment by brianleroux** [comment]
oh, ok, think there's a misunderstanding there. the scheduled function will only be invoked every 6 hours or so. if you want something to log every time you hit `get /` for example … then add a console.log statement to `src/http/get-index/index.js` and check out the logs for that function on the http functions page!

**Comment by fillipvt** [comment]
Ohh I see, I was indeed expecting something different 😅. Thank you for the clarification, and for being so quick to respond! 

Closing the issue as it is not a bug.

**Comment by brianleroux** [comment]
Cool! Np, always happy to help. No issue is too smol. =) Have fun and don't hesitate to come back if you need a hand.

Cheers,
Brian

**Comment by kristoferjoseph** [comment]
@fillipvt You were correct. This example should update the view count with each page refresh.
There was a syntax change in the http payload from `path` to `rawPath` 
Example app has been updated:
https://github.com/begin-examples/node-scheduled/blob/main/src/http/get-index/index.js#L5

You can fix your own repo by changing it here:
https://github.com/fillipvt/begin-scheduled-functions-app/blob/main/src/http/get-index/index.js#L5
and here:
https://github.com/fillipvt/begin-scheduled-functions-app/blob/main/src/http/get-index/index.js#L8


Thank you for reporting this issue

**Comment by fillipvt** [comment]
Ohhhh, that's great to know @kristoferjoseph, TYVM I was about to make a suggestion on the docs to be more specific with the `rate(6 hours)`, thinking that was the reason it was not being updated on each page refresh.

@brianleroux I'll be sure to ask a lot of questions! Just getting started
