### ISSUE TITLE
Add yarn.lock support

### ISSUE THREAD

**Issue by fillipvt** [smallwins/begin-community#58]
**Is your feature request related to a problem? Please describe.**

There's a build error without `package-lock.json`, [it happened right after I replaced](https://github.com/fillipvt/begin-scheduled-functions-app/commits/main) `package-lock.json` with `yarn.lock`
<img width="970" alt="Screen Shot 2020-10-30 at 7 47 16 PM" src="https://user-images.githubusercontent.com/16828078/97767250-fa5bff00-1ae8-11eb-8392-781700dfd5aa.png">

**Describe the solution you'd like**
I'm not totally sure if this is just some sort of configuration I'm missing, but I was not expecting an error due to the lack of `package-lock.json`. The enhancement here would be for this kind of error with yarn to not appear.

**Describe alternatives you've considered (if any)**
After looking around the only mention of `yarn` in `begin.com` is in the [Vue guide](https://docs.begin.com/en/guides/vue) so I haven't tried anything else TBH.

**Comment by ryanblock** [comment]
Hmm, sorry about that, we should support Yarn, I wrote the integration! I am out of town this weekend but will take a look first thing next week. Thank you for reporting! 💕

**Comment by ryanblock** [comment]
Oh, real quick, try adding Yarn to your dev deps, that may fix it!

**Comment by fillipvt** [comment]
I [just tried that](https://github.com/fillipvt/begin-scheduled-functions-app/commit/3fecc9238f67378e75f5ea93022239bb4f300e89), but it doesn't seem to do the trick.

**Comment by ryanblock** [comment]
Ok, thanks for your patience, it's been a hectic few days!

I've got this cornered, stand by for a fix shortly.

**Comment by ryanblock** [comment]
Good news, fix is live now, please let me know if you run into any issues! (You should be able to just hit the retry build button, no new builds necessary.)
